name: Pull Request on Branch Master

on:
  pull_request:
    branches: [master]

jobs:
  build-test-linter:
    name: Build, Unit Test, and Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run lint

  merge-code-to-the-master-branch:
    name: Auto merge
    needs:
      - build-test-linter
    runs-on: ubuntu-latest

    steps:
      - uses: everlytic/branch-merge@1.1.0
        with:
          github_token: ${{ github.token }}
          source_ref: ${{ github.ref }}
          target_branch: 'master'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'
