name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  pull_request_validation:
    name: Validate pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages  
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Run linter
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: run lint
      - name: Build project
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Run tests
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: test
